### ISSUE TITLE
CSP issue

### ISSUE THREAD

**Issue by phaistonian** [pmndrs/react-spring#1423] opened 2021-04-15 15:23 UTC
## 🐛 Bug Report

As of the [this commit](https://github.com/pmndrs/react-spring/commit/f3c4c0b7fbc9db4112e3722f3c05269b73b49b08#diff-bd9741bffd771a2193b84cd7317ae87f02c9d811e9b6aaba5d634a0e16a1fe1aR23-R25) React Spring won't work whenever a CSP without `'unsafe-eval'` directive is active.

## To Reproduce

Set content security policy (CSP) without `'unsafe-eval'` in `connect-src` directive.

**Comment by joshuaellis** [comment] 2021-04-15 15:25
Thanks for the report! Can you please provide a repo so we can test against?

**Comment by phaistonian** [comment] 2021-04-15 15:27
I am afraid now - this happened in our main repo and it's not one I can share.

It's really easy to repro, though.

All you need is to set a CSP and load RS.

Btw, this [is the culprit](https://github.com/pmndrs/react-spring/blob/f3c4c0b7fbc9db4112e3722f3c05269b73b49b08/packages/core/src/SpringRef.ts#L23-L25).

Apparently CSP treats `super('return arguments.callee._call.apply(arguments.callee, arguments)')` as eval.

**Comment by dbismut** [comment] 2021-04-19 21:50
@joshuaellis I guess we can try the Proxy method in this article instead https://hackernoon.com/creating-callable-objects-in-javascript-d21l3te1.

**Comment by steponas** [comment] 2021-04-26 11:52
I agree that this is an issue. The "unsafe eval" issue prevents the upgraded plugin from running in environments which have some thought put into their CSP rules.

**Comment by joshuaellis** [comment] 2021-04-26 12:06
An update, we're currently looking into how viable it is to use the `Proxy` method. We understand there comes some overhead and we want to gauge how much that overhead it is and how it impacts the library. 

If anyone has any suggestions how else we might tackle the issue, we'd love to hear it.

**Comment by chris-armstrong** [comment] 2021-04-27 01:15
I'm seeing this issue when running code through testcafe, which (probably) uses strict CSP rules to call out to the subject website under test using cross-origin calls

**Comment by crux153** [comment] 2021-04-29 04:49
Using `Proxy` will cause some issue with old browsers without ES6 support, such as IE11. While ES6 Proxy isn't fully polyfillable, I think this specific functionality can be supported as it only uses `apply` method of Proxy, which is supported by limited polyfill like [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill). Maybe it would be best option to figure out how [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill) handles it and embed it directly in `SpringRef` so that it can work without using Proxy.

**Comment by joshuaellis** [comment] 2021-05-09 20:48
As a rule we don't officially support IE11. AFAIK if you need to, you should run this module through `babel` but i've never tried it if I'm honest.

I'll be looking to implement this in a `beta` this week and see how it feels from there.

**Comment by phaistonian** [comment] 2021-05-11 07:47
@joshuaellis Will upgrade and get back to you soon enough :)

**Comment by phaistonian** [comment] 2021-05-11 08:51
It looks/works fine.

Can't test it on an IE (at the moment), though.

**Comment by joshuaellis** [comment] 2021-05-11 08:56
> As a rule we don't officially support IE11.

See above comment, this originally to do with a package `rafz` but now Proxy will be an issue too, to resolve this i'd imagine you need to run react-spring through babel.

**Comment by piotrblasiak** [comment] 2021-05-11 09:09
I am still getting CSP error with this beta.

Error:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at new SpringRef (react-spring-core.esm.js:1771)
    at react-spring-core.esm.js:1834```


Here my policy:

```
  'default-src': [ "'none'" ],
  'base-uri': [ "'none'" ],
  'manifest-src': [ "'self'" ],
  'script-src': [
    "'self'"
  ],
}
``

**Comment by joshuaellis** [comment] 2021-05-11 10:30
This is the code (taken from the built version) that is giving us issues:

```js
class SpringRef extends Function {
  constructor() {
    super();
    this.current = [];
    return new Proxy(this, {
      apply: (target, thisArg, args) => target._call(...args)
    });
  }

  _call(props) {
    deprecateDirectCall();
    this.start(props);
  }
}
```

Could it be the `extends Function` that could be the issue? Originally we didn't extend it from anything... 🤔 I'd love to understand why that would cause an issue...

**Comment by piotrblasiak** [comment] 2021-05-11 11:09
I'm not an expert but I know instantiating Function is banned, so instantiating anything extending Function is probably as well.

**Comment by joshuaellis** [comment] 2021-05-11 11:12
> I'm not an expert but I know instantiating Function is banned, so instantiating anything extending Function is probably as well.

You may not be an expert, but you've definitely taught me something! ⭐

**Comment by joshuaellis** [comment] 2021-05-11 22:04
I've opened a new PR that completely basically reverts the state of `SpringRef` to what i was before (no extending Function). but if anyones got a moment, it'd be good to see if you find being able to call `start()` like you did in v8 useful or not really anymore. See the PR for details.

**Comment by chris-armstrong** [comment] 2021-05-11 22:08
This has been causing me grief as well, and to be honest, I have a small amount of code that I want to move to v9, and the calling pattern is trivial to change as part of the API update, compared to the execution environment headaches that come from the implicit eval() used to maintain backwards compatibility.

**Comment by joshuaellis** [comment] 2021-05-11 22:12
@chris-armstrong thanks! To be honest I really did think the same, but the amount of people who seemed bewildered by the change at the time was crazy! Hopefully though, the PR will resolve this, I don't normally work in strict environments so wasn't aware of this, nor is there a way to test this yet!

**Comment by crux153** [comment] 2021-05-12 03:09
Currently I'm just patching `react-spring` to remove the callable behavior (which is deprecated and not being used in my codebase).

```js
{
  test: /node_modules\/@react-spring\/core/,
  loader: "string-replace-loader",
  options: {
    multiple: [
      {
        search: "class SpringRef extends Function",
        replace: "class SpringRef",
        strict: true,
      },
      {
        search: `super("return arguments.callee._call.apply(arguments.callee, arguments)");`,
        replace: "",
        strict: true,
      },
    ],
  },
}
```

I used webpack [string-replace-loader](https://github.com/Va1/string-replace-loader) but something like [patch-package](https://github.com/ds300/patch-package) would also work fine.

How about offering a flag to disable the callable behavior? I think we can do something like below.

```ts
export class SpringRef<State extends Lookup = Lookup> {
  static disableCallable: boolean = false;
  readonly current: Controller<State>[] = []

  constructor() {
    if (!SpringRef.disableCallable) {
      Function.call(this, 'return arguments.callee._call.apply(arguments.callee, arguments)');
    }
  }
}
```

Then set this flag at the script entry when using csp.

```ts
import { SpringRef } from "@react-spring/web";
SpringRef.disableCallable = true;
```

We might bundle a simple check to automatically set this flag.

```ts
try {
  new Function('');
  SpringRef.disableCallable = true;
} catch (e) {
  SpringRef.disableCallable = false;
}
```

**Comment by joshuaellis** [comment] 2021-05-12 09:18
Thanks for the suggestion @crux153, would you have to set `SpringRef.disableCallable` for everytime you try to use it? Because we call it internally on hooks such as `useSprings` 🤔  it might have to be a `Global` instead. If you're interested in creating a PR i'd be interested in seeing this!

**Comment by crux153** [comment] 2021-05-14 04:55
@joshuaellis `SpringRef.disableCallable` is a static property and only has to be set once, so there's no need to have a `Global`.

However, I found that it is not feasible to conditionally inherit from `Function`. I first thought it should be simple enough with prototype inheritance, but it seems like extending Function with prototype inheritance is massive pain without ES6 class. It IS possible, but Babel involves a lot of tricks to accomplish this and there will be performance penalties.

Most simple approach is to have two copy of SpringRef, one that extends Function and one not callable. Since multiple inheritance is not supported in JavaScript. I haven't found any way to accomplish this without code duplication.

**Comment by crux153** [comment] 2021-05-21 04:12
@joshuaellis Ok, I think I found a way of doing this.

```ts
function noUnsafeEval() {
  try {
    new Function('')
    return false
  } catch (e) {
    return true
  }
}

const ConditionalCallable = (() => {
  if ((window as any).REACT_SPRING_DISABLE_CALLABLE_REF || noUnsafeEval()) {
    return class {}
  } else {
    return class extends Function {
      constructor() {
        super(
          'return arguments.callee._call.apply(arguments.callee, arguments)'
        )
      }
    }
  }
})()

export class SpringRef<State extends Lookup = Lookup> extends ConditionalCallable {}
```

This will simply disable the callable behavior in CSP-enabled environments without `unsafe-eval`.

One can also disable it explicitly with by setting a global variable like
```js
window.REACT_SPRING_DISABLE_CALLABLE_REF = true
```

Using the same approach, we can also enable the `Proxy` method only when CSP is enabled.

You can see the full version [here](https://github.com/crux153/react-spring/blob/ce9e91316acc39645bca0a9cdbdb5b130fe029ca/packages/core/src/SpringRef.ts), and I'll create a PR if you like it.

**Comment by joshuaellis** [comment] 2021-05-26 09:32
Thanks @crux153 i've just released `9.2.0-beta.7` which involved re-writing SpringRef as a function with static methods instead of a class. 

It'd be great if anyone could try this and let me know if it's resolved the issue?

@simonauner
@piotrblasiak
@phaistonian

**Comment by phaistonian** [comment] 2021-05-26 09:50
@joshuaellis  Gave it a go. Did not work ;(

**Comment by joshuaellis** [comment] 2021-05-26 09:52
Interesting, I wonder why this would give us said error when we're not extending from `Function`. Would it be the static routes?

**Comment by phaistonian** [comment] 2021-05-26 09:55
@joshuaellis Let me try something else - there's a chance I might be not testing it properly. Will get back a bit later.

**Comment by phaistonian** [comment] 2021-05-26 11:15
@joshuaellis it seems it does not work, still. I am sure it will be dealt with eventually, though :)

**Comment by joshuaellis** [comment] 2021-05-26 11:18
Can you share any error messages? I'm really not sure why this wouldn't work considering we've removed the extension of `Function`.

**Comment by piotrblasiak** [comment] 2021-05-26 11:26
At first testing it works here! Good job! I'll let you know if I run into any other problem but so far so good.

**Comment by phaistonian** [comment] 2021-05-26 15:25
@joshuaellis somehow I still see this - not sure why (considering that you mentioned removing the Function extension).
<img width="379" alt="CleanShot 2021-05-26 at 18 23 43@2x" src="https://user-images.githubusercontent.com/796530/119687220-b26b4380-be4f-11eb-9e1e-de7439b45557.png">

<img width="332" alt="CleanShot 2021-05-26 at 18 23 29@2x" src="https://user-images.githubusercontent.com/796530/119687104-9a93bf80-be4f-11eb-8749-316d76f45588.png">

![image](https://user-images.githubusercontent.com/796530/119687293-c020c900-be4f-11eb-8a69-7962d5cb027c.png)

**Comment by joshuaellis** [comment] 2021-05-26 16:00
Odd, I just downloaded the latest beta and it's certainly not there, it should look something like this:
![image](https://user-images.githubusercontent.com/37798644/119693119-e50f3f00-be43-11eb-9a2e-ac3a4b548b36.png)

I hate being that guy and suggesting this, but have you tried a clean `npm` install? 😅

**Comment by phaistonian** [comment] 2021-05-27 04:26
@joshuaellis So, for this to work, I had to add a yarn resolution to the latest beta.

Not sure why (yet), but it did the trick.

Thank you - and apologies for the confusion.

**Comment by joshuaellis** [comment] 2021-05-27 08:16
It looks like the issue is resolved, it's released on `9.2.0-beta.7` for anyone looking for the fix, although today i'll be releasing `9.2.0` stable. So it'll be on there EOD. I'm going to close this, we can revisit if there are still issues, thank you to everyone who offered help and tested for me you're the real MVP.

**Closed by joshuaellis** 2021-05-27 08:16 UTC
Labels: bug, core, v9

**Comment by metart43** [comment] 2021-05-27 19:48
Can also confirm that **9.2.0** fixed this issue for me.

**Comment by thestephenmarshall** [comment] 2021-05-27 19:53
And another.. `9.2.0` has fixed it for me! 🎉
