### ISSUE TITLE
useChain seems to not orchestrate

### ISSUE THREAD

**Issue by Emiliano-Bucci** [pmndrs/react-spring#1578] opened 2021-06-21 19:42 UTC
## 🐛 Bug Report

As far as i understood, if only the first argument is passed to the `useChain` hook (the list of ref's), react-spring should orchestrate and start every animation at the end of the previous one. It seems that this isn't working as expected. 

## To Reproduce

Visit the react-spring official example and remove the second argument of the useChain hook.

https://codesandbox.io/s/e99i2?file=/src/index.js

## Environment

- `react-spring` 9.1.0

**Comment by joshuaellis** [comment] 2021-06-29 17:24
duplicate of #1512

**Closed by joshuaellis** 2021-06-29 17:24 UTC
Labels: duplicate
