### ISSUE TITLE
Leave transform animation on useTransition is not working

### ISSUE THREAD

**Issue by alexpuertasr** [pmndrs/react-spring#1180] opened 2020-10-20 08:06 UTC
## 🐛 Bug Report

The leave transform animation is not working

![gif-bug](https://user-images.githubusercontent.com/10731590/96558322-ccdaae80-12bb-11eb-8266-69866765987b.gif)

## To Reproduce

- Click the button twice and see how the animation on leave is not working

## Expected behavior

The animation is working on leave like the opacity animation

## Link to repro

https://codesandbox.io/s/issue-with-react-spring-v9-transform-lobc0?file=/src/App.jsx

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.14.0

**Comment by aleclarson** [comment] 2020-10-20 13:07
Duplicate of #1159

**Closed by aleclarson** 2020-10-20 13:07 UTC

**Comment by Clago** [comment] 2021-04-16 02:20
change 0 to 0px
