### ISSUE TITLE
[SSR] Controllers are not garbage collected correctly

### ISSUE THREAD

**Issue by RafalFilipek** [pmndrs/react-spring#778] opened 2019-08-10 20:31 UTC
# Bug report

## Describe the bug

Hi,

I found this bug in my Next.js app, but we think it's not related to NextJS itself but rather SSR in general.

Let's go straight to example:

## To Reproduce

* clone this repo - https://github.com/RafalFilipek/nextjs-react-spring-bug
* `yarn install`
* `yarn build`
* `yarn start`

This command will start production version of application with `--inspect` flag to enable NodeJs debugger.

* open `[http://localhost:3000](http://localhost:3000)` in Chome
* open DevTools and click NodeJS logo on the left

<img width="327" alt="Screenshot 2019-08-02 at 16 29 46" src="https://user-images.githubusercontent.com/80960/62379541-7151c300-b547-11e9-9552-1180fde3417d.png">

This will open Dedicated NodeJS debugger. 

* open `Memory` tab, select `Heap Snapshot` and click `Take Snapshot`. You will get something like this:

![Screenshot 2019-08-02 at 16 31 37](https://user-images.githubusercontent.com/80960/62379656-a9f19c80-b547-11e9-87ca-a8dba8f2c4ee.png)

Now it's time to make some requests. I'm using [autocannon](https://www.npmjs.com/package/autocannon), but you can use any tool like `ab`.

```
autocannon -c 50 -a 1000 http://localhost:3000 
```

Now you can take second snapshot. It should be much bigger:

![Screenshot 2019-08-02 at 16 35 21](https://user-images.githubusercontent.com/80960/62380056-a3aff000-b548-11e9-9e48-b12fa3110638.png)

After 4K requests you will see that there is a lot of allocations in `array` part. For some reason there are many allocations of `Controller` class from `react-spring`.  I have no idea why. 

![Screenshot 2019-08-02 at 16 42 20](https://user-images.githubusercontent.com/80960/62380025-9430a700-b548-11e9-9d71-2a6b76ad0172.png)

It looks like new Controller class is created for each request, but old instances are not garbage collected. ([this](https://github.com/react-spring/react-spring/blob/master/src/animated/FrameLoop.ts#L6) and [this](https://github.com/react-spring/react-spring/blob/master/src/animated/FrameLoop.ts#L123) lines?)

Now let's compare snapshots in this same application but without `getInitialProps` in `_app.js` - no SRR.

After 10K request you will get something like this:

![Screenshot 2019-08-02 at 16 48 22](https://user-images.githubusercontent.com/80960/62380222-0f925880-b549-11e9-807d-32727b4e879a.png)

- `Snapshot 1` - after `yarn start`
- `Snapshot 2` - after 10K req
- `Snapshot 3` - after `GC`

## System information

- OS: macOs / Docker 12.4.0-alpine
- Version of Next.js: `9.0.2`, `9.0.3`
- Version of react-spring `8.0.27,` `9.0.0-beta.31`
- Version of React: `16.8.6`

Thank you

**Comment by RafalFilipek** [comment] 2019-08-20 07:08
Same with `9.0.0-beta-33`

<img width="901" alt="Screenshot 2019-08-20 at 09 08 00" src="https://user-images.githubusercontent.com/80960/63325245-0c111680-c32a-11e9-9ac8-e8ca93a86fce.png">

**Comment by RafalFilipek** [comment] 2019-08-20 07:36
@aleclarson I think the problem is that `stop` function from `FrameLoop` is not called. 

When I add `this.controllers.clear();` in `start` method of `FrameLoop` there is no leak (I know it's not a solution).

Thank you

**Comment by VindulaF** [comment] 2019-08-20 13:56
Running into the same issue here, our Next.js app server ran into OOM issues constantly because of this, we were using `react-spring: 8.0.27` and `next: 7.0.2`.

**Comment by RafalFilipek** [comment] 2019-08-28 18:12
@aleclarson is there anything I can try to solve this issue? I know you are quite busy with v9 so maybe some hints :)

Thank you

**Comment by RafalFilipek** [comment] 2019-09-15 09:04
@aleclarson Thanks, I'll wait for new beta :) I can see you moved controllers Set inside FrameLoop. Maybe it will help.

**Comment by DeviousM** [comment] 2019-11-05 14:57
I can confirm that this happens on Razzle & After.js combo and on the newest version of the beta (`9.0.0-beta.34`).
![image](https://user-images.githubusercontent.com/9259157/68218738-1962a680-ffe5-11e9-8aa2-f69ecc4d4a42.png)

- `Snapshot 1` - Right after node.js server starts
- `Snapshot 2` - After first request
- `Snapshot 3` - After 2600 requests. 

Heap has grown substantially and after few hours on a production server it causes a crash beacuse, quite obviously, OOM. 

How far is it from fixing that issue and can we expect it to be fixed in the newest beta?

**Comment by aleclarson** [comment] 2019-11-05 15:42
@DeviousM Can you provide a minimal reproduction case? That would be super helpful as I'm not using SSR with `react-spring` anywhere right now. Also, please try with the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404) too.

**Comment by aleclarson** [comment] 2019-11-05 15:42
@DeviousM I'm not using react-spring with SSR anywhere right now. Have you tried with the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404)?

**Comment by DeviousM** [comment] 2019-11-05 15:50
Yup, I've just tried the latest canary and got this error:
```
TypeError: Cannot read property 'ref' of null
    at useTransition (/stonly/apps/stonly-player/stonly/node_modules/@react-spring/core/index.cjs.js:2211:1)
    at /stonly/apps/stonly-player/build/webpack:/stonly-commons/components/HOC/Panel/Panel.js:104:1
    at processChild (/stonly/apps/stonly-player/build/webpack:/stonly/node_modules/react-dom/cjs/react-dom-server.node.development.js:3206:1)
    at resolve (/stonly/apps/stonly-player/build/webpack:/stonly/node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:1)
    at ReactDOMServerRenderer.render (/stonly/apps/stonly-player/build/webpack:/stonly/node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:1)
    at ReactDOMServerRenderer.read (/stonly/apps/stonly-player/build/webpack:/stonly/node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:1)
(...rest is useless)
```
And the `Panel.js` component that's throwing that error is actually using the `useTransition` hook like that:
```
/* ...rest ommited... */
const positionMap = {
  left: 'translate3d(-100%, 0, 0)',
  right: 'translate3d(100%, 0, 0)',
};

const transition = useTransition(show, null, {
  from: { transform: positionMap[position] },
  enter: { transform: 'translate3d(0,0px,0)' },
  leave: { transform: positionMap[position] },
  config: { mass: 1, tension: 500, friction: 47 },
});
/* ...rest ommited... */
```
I'll provide a minimal reproduction case in a moment.

**Comment by DeviousM** [comment] 2019-11-05 16:22
Alright, @aleclarson, I've created a repo that allows you to clone it and run the heap test locally: https://github.com/DeviousM/react-spring-ssr-issues

To reproduce the issue clone the project, then `yarn` to install everything and then `yarn start` to start it up. When you have it running, you can access the node.js's profiler tool in Chrome on `localhost:7776`. (you can find it at chrome://inspect)
Take a first heap snapshot after the app starts up and you'll see that it's pretty clean.
![image](https://user-images.githubusercontent.com/9259157/68225140-410b3c00-fff0-11e9-8bb9-e3ba0571925d.png)

Then to simulate some load on the server download a tool like `siege` (that's what I'm testing with) and let it swarm the server for around 45 seconds (if you download `siege` then commad is `siege http://localhost:3005`). You can watch live how the server's heap size is growing to end up at least twice as big, mostly clogged by FrameLoop:
![image](https://user-images.githubusercontent.com/9259157/68225226-65ffaf00-fff0-11e9-8fe7-bb567f97f1e3.png)

Let me know if you have any more questions about my example.
EDIT:// I pushed to the repo, because I kind of forgot to do that one, specific thing 😅

**Comment by aleclarson** [comment] 2019-11-05 16:46
> Yup, I've just tried the latest canary and got this error:

That's because the function signature of `useTransition` has changed. More info here: #809

I gave @RafalFilipek's repro a try with both `9.0.0-beta.34` and `9.0.0-canary.808.9.7e75a67`.

After 10k requests, it went from 5.2MB to 44.5MB when using `9.0.0-beta.34`. After installing the latest canary, it went from 5.2MB to only 8.8MB. There may or may not still be a small leak, but that's a great improvement.

You can see my fork of the repro here: https://github.com/aleclarson/repro/commits/react-spring-778

**Comment by DeviousM** [comment] 2019-11-05 16:50
Oh, alight! Let me try it then, I'll report back with results.

**Comment by DeviousM** [comment] 2019-11-05 17:50
Yep, it fixes the memory leak! Thanks! 

BTW - is there a list of all of the API's that have changed? Because there are quite few places where my app now looks bad (ie. Trail now kind of broke)

**Comment by RafalFilipek** [comment] 2019-11-06 18:32
Hi,

I've just tested my example with `9.0.0-canary.808.9.7e75a67`. 40K requests later there is no sign o any leak. Some pick around 0.5 MB can be related to internal NodeJS cache system or something like that.

@aleclarson I think we can close this issue. I'll monitor new versions actively :)

Thank you!

**Comment by DeviousM** [comment] 2019-11-06 18:48
Yup, on our production build the SSR server didn't grow almost at all. 

I agree that we could close the issue, though shouldn't we wait with it until the v9 or at least a new beta is released? Because currently it's still a case for normal `react-spring` and `react-spring@next` installation.

**Comment by aleclarson** [comment] 2019-11-13 22:20
> BTW - is there a list of all of the API's that have changed?

Not yet. I'll write one up when we're closer to v9 being released.

> Because there are quite few places where my app now looks bad (ie. Trail now kind of broke) + is there a way to get index of the item in the new Transition implementation?

Could you ask these questions separately in [our Spectrum community](https://spectrum.chat/react-spring?tab=posts)? Thanks 👍

**Comment by v-Bauer** [comment] 2020-02-19 11:56
Hi,
I have already written in another thread with the same bug.
is there a possibility that this bug is fixed in v8? Unfortunately, we can't update to v9beta because of other bugs and the canary version doesn't seem to be suitable for production use yet and doesn't have any documentation.
We would also be willing to pay / donate for the fix in the current stable version. 😊

**Comment by topaxi** [comment] 2020-03-02 11:52
With the cause being known that controllers within https://github.com/react-spring/react-spring/blob/66087e18b64d6c6d5fd75f6d84e85ed59714769d/src/animated/FrameLoop.ts#L6 are not being cleaned up, what would we need to get this fixed? I'm up for helping out, but I'm not 100% certain where I should clean this up? Either the Controller class should remove itself when being stopped/destroyed or wherever they are being created they should be cleaned up.

Any help from the maintainers would be great, I'd be happy to help out on a weekend of mine, should I contact you via spectrum?

**Comment by KB1RMA** [comment] 2020-03-30 17:46
I commented on Damian's PR as well but I wanted to bring this issue back up again as I've traced a memory leak in my SSR application to the same place.

![image](https://user-images.githubusercontent.com/223527/77944210-8cb6ce80-728c-11ea-9cd6-439709b9fa4e.png)

It's certainly an ugly hack, but perhaps that's okay?

**Comment by aleclarson** [comment] 2020-05-06 04:29
If anyone has time, please try with `9.0.0-rc.1` and let me know how it goes. 👍 

More info: #985

**Comment by topaxi** [comment] 2020-05-06 07:39
`9.0.0` breaks compatibility and has some issues and last time I tried it, it broke on IE11. A backported fix to version `8.x` would be highly appreciated.

**Comment by aleclarson** [comment] 2020-05-09 14:00
@topaxi v9 is more stable than v8 at this point. I recommend migrating to it and reporting any bugs you may find. I'll fix 'em up real quick ;)

**Comment by joselcc** [comment] 2020-09-29 23:00
It looks like Controllers are not the only ones not being garbage collected 
<img width="1191" alt="Screen Shot 2020-09-30 at 8 37 44 am" src="https://user-images.githubusercontent.com/7456941/94625113-54578200-02fb-11eb-846a-ad0835970fb1.png">

**Comment by schriker** [comment] 2021-01-11 09:31
Hi, it seems like i'm having the same issue. Any updates on this?

### Stack
- react: 17.0.1
- next.js: 10.0.5
- react-spring: 8.0.27

![Zrzut ekranu 2021-01-11 o 10 25 37](https://user-images.githubusercontent.com/28902144/104163939-7af77f80-53f7-11eb-95a7-7d001772bf33.jpg)

**Comment by joshuaellis** [comment] 2021-03-18 14:23
closing due to inactivity, looks like it was fixed in rc3. please use discussions or discord if you want more help or please consider creating a PR if you want to add a feature 😄

**Closed by joshuaellis** 2021-03-18 14:23 UTC
Labels: SSR, bug
