### ISSUE TITLE
[bug]: useTransition with routes causes react error if using this hook inside on of the routes component

### ISSUE THREAD

**Issue by newilu** [pmndrs/react-spring#1902] opened 2022-05-25 15:05 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

when using useTransition with location for Routes component (trying to implement page transition) and inside one of the components using same hook react gives following error - Rendered more hooks than during the previous render.
doing page transitions according to docs and all works fine if you are not using any of react-spring hooks inside your components, but how to use page transitions + elements transitions??

### To Reproduce

const location = useLocation()
const transitions = useTransition(location, { ... })
return transitions((props, item) => (
  <animated.div style={props}>
    <Routes location={item}>
      <Route path="/a" element={<A />} />
      <Route path="/b" element={<B />} />
      <Route path="/c" element={<C />} />
    </Routes>
  </animated.div>
))

and try to use useTransition hook inside component A

### Expected Behaviour

all works fine

### Link to repo

this is a private repo, i have no perms to show code

**Comment by joshuaellis** [comment] 2022-05-25 15:06
Please provide an actual reproduction of the issue such as a codesandbox otherwise I cannot investigate the issue.

**Comment by joshuaellis** [comment] 2022-06-07 06:46
closing due to insufficient reproduction.

**Closed by joshuaellis** 2022-06-07 06:46 UTC
Labels: type: needs repro, template: bug
