### ISSUE TITLE
[bug]: You may need additional loader error showing in terminal when i did yarn add @nivo/core @nivo/bar in my react app 

### ISSUE THREAD

**Issue by Znoy108x** [pmndrs/react-spring#2154] opened 2023-05-09 06:48 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

**Error Message**

./node_modules/@react-spring/web/dist/esm/index.js 113:11
Module parse failed: Unexpected token (113:11)

File was processed with these loaders:

 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js

You may need an additional loader to handle the result of these loaders.
>     this.transforms = I;
>     }
>     _value = null;
>     get() {
>     return this._value || (this._value = this._get());

Please help me resolve this issue !! 

### To Reproduce

i installed the nivo chart package in my react app and encountered this issue 
command : 
yarn add @nivo/core @nivo/bar

### Expected Behaviour

-

### Link to repo

-

**Comment by Jabberrwocky** [comment] 2023-05-17 20:04
I ran into a similar error message after upgrading from version 9.2.4 to 9.7.2.

```
./node_modules/@react-spring/web/dist/esm/index.js 119:9
Module parse failed: Unexpected token (119:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   _value = null;
| 
|   get() {
```

**Comment by sanchit3008** [comment] 2023-06-05 12:09
Facing the same issue 

> ERROR in ./node_modules/@react-spring/web/dist/esm/index.js 1:2829
Module parse failed: Unexpected token (1:2829)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders****

**Comment by joshuaellis** [comment] 2023-06-07 07:43
closing due to a lack of reproduction supplied – if someone can provide a minimal reproduction, we can revisit this :)

**Closed by joshuaellis** 2023-06-07 07:43 UTC
Labels: type: needs repro, template: bug
