### ISSUE TITLE
Interpolated float value is converted to integer on re-render without any change

### ISSUE THREAD

**Issue by swashata** [pmndrs/react-spring#1564] opened 2021-06-10 02:44 UTC
## 🐛 Bug Report

Let's say I want to animated between the number `0` and `100` and I want to display a float value with a precision of `2`. For that I do something like 

```jsx
function Counter({ value }) {
  const valueSpring = useSpring({
    from: { value: 0 },
    to: { value },
    config: config.stiff
  });

  return (
    <p>
      <animated.span>
        {valueSpring.value.to((num) => num.toFixed(2))}
      </animated.span>
    </p>
  );
}
```

Notice the interpolation `{valueSpring.value.to((num) => num.toFixed(2))}`. Now it works as expected on first render when the actual value is an integer. On first render, the resulting value is `100.00`. But due to so some changes in parent, if the component re-renders without the value being changed, the output becomes `100`. It does not take into consideration of the interpolated value.

## To Reproduce

1. Kindly go to this codesandbox: https://codesandbox.io/s/inspiring-jackson-m457i?file=/src/App.js
2. At first, the counter shows `100.00`.
3. Click on the `Force Render` button.
4. The counter would now show `100` instead of `100.00`. The same happens with other integer type values too.

Surprisingly if the value itself is a float (like the last button that says `499.99`) the output remains the same.

This could be related to #1461

## Expected behavior

The output should always show the interpolated value.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/inspiring-jackson-m457i?file=/src/App.js)

## Environment

- `@react-spring/web` v9.2.3
- `react` v17.0.2

**Comment by joshuaellis** [comment] 2021-06-10 06:05
This is a duplicate of #1461

**Closed** 2021-06-10 06:05 UTC
Labels: duplicate
