### ISSUE TITLE
react-spring not working with NextJS

### ISSUE THREAD

**Issue by mkhoussid** [pmndrs/react-spring#1176] opened 2020-10-14 10:19 UTC
## 🐛 Bug Report
Component does not render content

## To Reproduce
I'm trying to reproduce [this](https://codesandbox.io/s/j0y0vpz59?file=/src/index.js:0-3350) example, however it does not seem to render the content with NextJS.

[Codesandbox](https://codesandbox.io/s/react-overlay-images-react-spring-bug-forked-q26b5?file=/pages/index.js) with react-spring v9

## Environment

- `react-spring` v89.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by wanjas** [comment] 2020-10-23 07:34
Similar story for me. 
 ``` "next": "9.5.5", "react-spring": "9.0.0-rc.3"```
In `development` simple animation works fine but silently fails in `production` build. 
8.0.27 works everywhere. 

In my case component is **not** rendered on the server so it is not related to SSR I think.

```
const props = useSpring({
      from: {
        top: 25
      },
      to: {
        top:0,
      },
      config: config.wobbly,
    });

<animated.div style={props}>....</animated.div>
```

**Comment by TheSonOfThomp** [comment] 2020-12-08 19:39
I'm having issues as well. Works fine locally using `next dev`, but fails to render when I run a dev build with `next build`. Nothing outputted in the console, just no animation in the browser

**Comment by mrgoonie** [comment] 2020-12-09 07:59
I think it's a duplicate of https://github.com/pmndrs/react-spring/issues/1078

There is a workaround here while waiting for the next release:
https://github.com/pmndrs/react-spring/issues/1078#issuecomment-677528907

**Closed** 2021-03-18 17:30 UTC
Labels: SSR, potential bug, v9
