### ISSUE TITLE
Strange behavior with skipAnimation in v9.0.0-rc.3

### ISSUE THREAD

**Issue by cedricdelpoux** [pmndrs/react-spring#1224] opened 2020-12-06 18:09 UTC
## 🐛 Bug Report

I tried `skipAnimation` in `v9.0.0-rc.3`
```
import {Globals, useTrail} from "react-spring"

Globals.assign({
  skipAnimation: true,
})
...
const animations = useTrail(10, {
    from: {opacity: 0},
    to: {opacity: 1},
  })
```

But it does not work as I expected. My components are initialized with `opacity: 0` and go to `opacity: 1` without animations. 

## Expected behavior

It should be initialized with the `to` property because it seems buggy

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.13.1

**Comment by Rohanhacker** [comment] 2021-03-22 12:30
It's working fine for me. I am unable to reproduce.

**Comment by joshuaellis** [comment] 2021-03-22 14:45
> It's working fine for me. I am unable to reproduce.

thanks for looking @Rohanhacker, lets close this one then.

**Closed by joshuaellis** 2021-03-22 14:45 UTC
Labels: bug, v9
