### ISSUE TITLE
[bug]: Storybook build breaks after upgrade to version 9.7.1

### ISSUE THREAD

**Issue by alpfilho** [pmndrs/react-spring#2118] opened 2023-03-07 14:32 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.1

### What's Wrong?

Upgrade @react-spring/web version to version 9.7.1 causes build break.
Downgrading to 9.6.1 solves the issue.

![image](https://user-images.githubusercontent.com/17249907/223451919-3ec1d3bc-2f1d-4485-808c-5207911a15a5.png)

### To Reproduce

1. Start a new storybook project with webpack 4 builder
2. Install react-spring/web 9.7.1

### Expected Behaviour

Normal build without errors

**Comment by joshuaellis** [comment] 2023-03-07 14:34
Can you share a github repo with your issue please? Thanks!

**Comment by tandrasi** [comment] 2023-03-13 02:59
Same issue here, but I'm using SPFx to build a react app for SharePoint Online. We're on the latest SPFx version (1.16.1) using React 17.0.1. Is this react-spring issue due to requiring React 18?

**Comment by bpinto** [comment] 2023-03-16 11:33
@joshuaellis do you have access to a remote browser environment? Or old browsers I guess.

Picking [any](https://codesandbox.io/s/v1i1t) example from https://react-spring.dev and trying to run on iOS 13 Safari causes similar errors to be thrown.

<img width="456" alt="Screenshot 2023-03-16 at 11 33 22" src="https://user-images.githubusercontent.com/526122/225604501-7dfdd7d3-6195-40ef-b8d7-12239e9722e8.png">

**Comment by joshuaellis** [comment] 2023-04-09 07:46
Closing due to no reproduction provided. If someone can provide a reproduction e.g. codesandbox / stackblitz we can reopen this issue.

**Closed by joshuaellis** 2023-04-09 07:46 UTC
Labels: type: needs repro, template: bug

**Comment by jphawk** [comment] 2023-04-24 08:01
We have absolutely the same issue in our project after updating `react-spring` to version 9.7.1, so I had to downgrade to 9.6.1. Storybook stopped working on Safari bellow version 14 with the following error thrown: 
```
[Error] SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
(anonymous function) (964.25bc0b4b.iframe.bundle.js:2)
```
Our current setup is 

react@17.0.2
storybook@6.5.16
typescript@4.9.5
webpack@5.80.0
