### ISSUE TITLE
Animating CSS rotate transforms "snap" into its final value instead of smoothly animating

### ISSUE THREAD

**Issue by louh** [pmndrs/react-spring#875] opened 2019-11-28 19:51 UTC
## 🐛 Bug Report

Using react-spring to rotate a box with a CSS transform, the animation value "snaps" into the final position abruptly, near the very end of the animation, seemingly skipping a lot of values in between. 

(Following up from my Spectrum post, here: https://spectrum.chat/react-spring/general/css-transform-rotate-value-snaps-abruptly-at-the-end-of-the-animation~1f9d06d9-9410-4e95-b358-aad5a687af68)

## To Reproduce

Minimal sample code (See also CodeSandbox, below):

```jsx
import React from "react";
import { useSpring, animated } from "react-spring";

export default function TestRotate(props) {
  const spring = useSpring({
    from: {
      transform: 'rotateZ(0deg)'
    },
    to: {
      transform: 'rotateZ(360deg)'
    },
    config: {
      mass: 1,
      tension: 10,
      friction: 10
    }
  });

  return <animated.div className="test-box" style={spring} />;
}
```

## Expected behavior

I expect the CSS rotation value to smoothly animate into its final position.

## Link to repro (highly encouraged)

https://codesandbox.io/embed/elastic-night-w0b0b

In this example, I also am outputting a "raw" numerical value, demonstrating that this apparently only happens with the CSS transform, and not while animating a numerical value.

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x

Thanks!

**Comment by aleclarson** [comment] 2019-12-01 15:00
Bug confirmed in v9. As a workaround you can use `interpolate`, I think:
```ts
const {rotateZ} = useSpring({
    from: {
      rotateZ: 0
    },
    to: {
      rotateZ: 360
    },
  });

return (
  <animated.div style={{
    transform: rotateZ.interpolate(z => `rotateZ(${z})`)
  }} />
);
```

LMK if that works.

**Comment by louh** [comment] 2019-12-01 16:24
`interpolate` works perfectly. Exactly what I needed, thank you!

**Comment by Kadrian** [comment] 2020-04-15 20:52
I've got the same issue, but with a regular `rotate`. `interpolate` fixed it, but now I'm wondering: How do I conditionally start the interpolation?

**Comment by aleclarson** [comment] 2020-05-09 14:26
@Kadrian In v9, the `interpolate` callback runs whenever `rotateZ` is changed. So to postpone the interpolation, you would postpone the animation of `rotateZ`. In v9, you can do that with the `cancel` prop (see [here](https://aleclarson.github.io/react-spring/v9/#The-cancel-prop)).

**Comment by YassienW** [comment] 2020-12-18 11:57
Is this going to be fixed in the v9 final release?

**Comment by YassienW** [comment] 2021-01-07 12:49
This seems to be the case for other properties as well, in my example i'm animating `top` value and i experience the same snapping

**Comment by joshuaellis** [comment] 2021-04-25 21:46
I haven't seen this issue in `v9` if it is, let's reopen with a fresh bug report.

**Closed by joshuaellis** 2021-04-25 21:46 UTC
Labels: bug, v9
