### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by Bitha007** [pmndrs/react-spring#1189] opened 2020-11-04 09:03 UTC
## To Reproduce

```
import React from "react";
import { useSpring, animated } from "react-spring";

function Animation() {
  return (
    <div>
      Animation
      <AnimationOne />
    </div>
  );
}

function AnimationOne() {
  const animation = useSpring({
    from: { opacity: 0 },
    to: { opacity: 1 },
  });

  const colorAnimation = useSpring({
    from: { color: "blue" },
    to: { color: `rgb(255,0,0)` },
  });
  const multiAnimation = useSpring({
    from: { opacity: 0, color: "red" },
    to: [
      { opacity: 1, color: "#ffaaee" },
      { opacity: 1, color: "red" },
      { opacity: 0.5, color: "#008000" },
      { opacity: 0.8, color: "black" },
    ],
  });

  const props = useSpring({
    to: [
      { opacity: 1, color: "#ffaaee" },
      { opacity: 0, color: "rgb(14,26,19)" },
    ],
    from: { opacity: 0, color: "red" },
  });

  return (
    <div>
      <animated.h1 style={animation}>Hello World</animated.h1>
      <animated.h1 style={colorAnimation}>Hello World</animated.h1>
      <animated.h1 style={multiAnimation}>Hello World</animated.h1>
    </div>
  );
}

export default Animation;
```
This throws an error

```
Type '{ opacity: SpringValue<number>; }' is not assignable to type '{ alignContent?: "initial" | "end" | "baseline" | "inherit" | "start" | "center" | "-moz-initial" | "revert" | "unset" | "normal" | "space-around" | "space-between" | "space-evenly" | ... 4 more ... | undefined; ... 786 more ...; matrix3d?: readonly [...] | ... 1 more ... | undefined; }'.
  Types of property 'opacity' are incompatible.
    Type 'SpringValue<number>' is not assignable to type '"initial" | "inherit" | "-moz-initial" | "revert" | "unset" | FluidValue<Globals, any> | undefined'.
      Type 'SpringValue<number>' is not assignable to type 'FluidValue<Globals, any>'.
        The types returned by 'get()' are incompatible between these types.
          Type 'number' is not assignable to type 'Globals'.  TS2322

    32 |   return (
    33 |     <div>
  > 34 |       <animated.h1 style={animation}>Hello World</animated.h1>
       |                    ^
    35 |       <animated.h1 style={colorAnimation}>Hello World</animated.h1>
    36 |       <animated.h1 style={multiAnimation}>Hello World</animated.h1>
    37 |     </div>

```

## Environment
 "react": "^16.13.1",
 "react-dom": "^16.13.1",
 "react-spring": "^9.0.0-rc.3",

**Comment by aleclarson** [comment] 2020-11-04 16:04
Duplicate of #1102

**Closed by aleclarson** 2020-11-04 16:04 UTC
