### ISSUE TITLE
[bug]: Animation hangs and gets stuck

### ISSUE THREAD

**Issue by Amir-Latif** [pmndrs/react-spring#1884] opened 2022-05-02 19:52 UTC
### Which react-spring target are you using?

- [x] `@react-spring/web`

### What version of react-spring are you using?

9.4.4

### What's Wrong?

I am using this simple animation and it gets stuck at opacity 0.966666

```import { useSpring, animated } from 'react-spring'

function App() {
  const props = useSpring({ to: { opacity: 1 }, from: { opacity: 0 } })
  return <animated.div style={props}>I will fade in</animated.div>
}```

**Comment by joshuaellis** [comment] 2022-05-02 21:28
Please provide a reproduction of the issue (preferably a codesandbox)

**Comment by joshuaellis** [comment] 2022-06-07 07:04
closing due to insufficient reproduction.

**Closed by joshuaellis** 2022-06-07 07:04 UTC
Labels: type: needs repro, template: bug

**Comment by nz-chris** [comment] 2022-07-01 01:42
> closing due to insufficient reproduction.

I will try and make a reproduction later when I'm not at work, but I can confirm I can reproduce this.
If it leave my browser tab open for long enough, it will eventually hang (sometimes it happens faster than other time).
Then, when I pause scripts, I can see in the call stack that the browser was stuck in react-spring code.
