### ISSUE TITLE
[bug]: ESM failed to resolve with Webpack

### ISSUE THREAD

**Issue by zkylearner** [pmndrs/react-spring#2097] opened 2023-02-24 08:01 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0

### What's Wrong?

ERROR in ./node_modules/@react-spring/core/dist/index.mjs 1596:0-45

Module not found: Error: Can't resolve '@react-spring/types/animated' in '.../my-app/node_modules/@react-spring/core/dist'
Did you mean 'animated.js'?
BREAKING CHANGE: The request '@react-spring/types/animated' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

### To Reproduce

Code running locally has an error

### Expected Behaviour

no error

### Link to repo

https://codesandbox.io/s/bold-mahavira-y26di2?file=/src/App.js

**Comment by joshuaellis** [comment] 2023-02-24 08:11
I cant see an error in the reproduction?

**Comment by LoicHuart** [comment] 2023-02-24 08:24
I have the same error on my project.
It's a react app with typescript.
And I use craco to create aliases and be able to import my files with @/.
it may be due to this configuration, I'm not sure.


```
// craco.config.js
const path = require('path');

module.exports = {
    webpack: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
    },
};
```

**Comment by GivenCui** [comment] 2023-02-24 08:45
I also face this error today. Before that, it was working fine.

**Comment by joshuaellis** [comment] 2023-02-24 08:46
Please stop saying you're getting the error and not providing a reproduction – it's really unhelpful and doesn't make anything happen quicker.

**Comment by nongtiny** [comment] 2023-02-24 09:14
> Please stop saying you're getting the error and not providing a reproduction – it's really unhelpful and doesn't make anything happen quicker.

@joshuaellis 

I'm sorry. What kind of reproduction do you want to see?

For the test URL, I can't build the reproduction for you because When I do `react-scripts build,`  it has this error also. Build is failed.

I'm not sure if this can help you, but the `@react-spring/types` has an update last 13 hours ago. I don't know that this might be the case or not. ref: https://www.npmjs.com/package/@react-spring/types?activeTab=versions

Node version: 16.17.1

My dependencies

![image](https://user-images.githubusercontent.com/21060275/221139355-d43d10d6-bc8f-4388-978e-8e7e1ec39249.png)


```
"dependencies": {
    "@headlessui/react": "1.7.10",
    "@react-spring/types": "9.6.1",
    "@react-spring/web": "9.7.0",
    "@react-three/drei": "9.43.3",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@use-gesture/react": "^10.2.22",
    "autoprefixer": "^10.4.13",
    "axios": "^1.2.4",
    "camera-controls": "^1.37.4",
    "leva": "^0.9.34",
    "lodash": "^4.17.21",
    "postcss": "^8.4.19",
    "react": "^18.2.0",
    "react-custom-scrollbars-2": "^4.5.0",
    "react-dom": "^18.2.0",
    "react-loader-spinner": "^5.3.4",
    "react-router-dom": "^6.4.4",
    "react-scripts": "5.0.1",
    "react-three-fiber": "6.0.13",
    "reactjs-popup": "^2.0.5",
    "tailwindcss": "^3.2.4",
    "three": "0.146.0",
    "web-vitals": "^2.1.4"
  },
```

**Comment by joshuaellis** [comment] 2023-02-24 09:23
@nongtiny, sounds like you're using CRA? So perhaps just a github repo that has CRA and `@react-spring/web` installed and trying to do "something" will be enough – appreciate because it's CRA it might not be possible with codesandbox.

**Comment by nongtiny** [comment] 2023-02-24 09:32
Yes I'm using CRA.

Is there any workaround to avoid or fix this problem?

**Comment by joshuaellis** [comment] 2023-02-24 09:35
> Yes I'm using CRA.
> 
> Is there any workaround to avoid or fix this problem? @joshuaellis
> 
> Will do a Repo for you soon.

It seems an issue with CRA's webpack configuration. This follows specs on delivering ESM & CJS so i'm not totally sure to be honest.

**Comment by nongtiny** [comment] 2023-02-24 09:49
@joshuaellis 

Here you go https://github.com/nongtiny/test-cra-reactspring-issue/tree/main

Thanks a lot for your fast reply and support!

**Comment by joshuaellis** [comment] 2023-02-24 10:01
Isn't this the issue – https://github.com/facebook/create-react-app/issues/11865? While I understand the `react-spring` has caused the break the fault lies with CRA. Our ESM / CJS implementation was incorrect so it's been fixed properly... 🤔 

The solution it seems whilst i'm not sure how you would do it, is to add:
```ts
{
  test: /\.m?js/,
  resolve: {
    fullySpecified: false
  }
}
```

to your webpack configuration...

**Comment by LoicHuart** [comment] 2023-02-24 10:05
I have already tried this configuration in my craco.config.js file without success
```
const path = require('path');

module.exports = {
    webpack: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
        rules: [
            {
                test: /\.m?js/,
                resolve: {
                    fullySpecified: false
                }
            },
        ],
    },
};
```

**Comment by joshuaellis** [comment] 2023-02-24 10:12
@LoicHuart I don't think that's how you do it is it? Have you looked at the documentation? https://craco.js.org/docs/configuration/webpack/

**Comment by bpinto** [comment] 2023-02-24 10:19
@joshuaellis that indeed solves the problem. Does that mean that the distributed `.mjs` file is not using fully specified path and so webpack is not able to find the file?

What I haven't been able to understand yet is why webpack using `.mjs` file by default instead of `.js`...

**Comment by joshuaellis** [comment] 2023-02-24 10:21
>@joshuaellis that indeed solves the problem. Does that mean that the distributed .mjs file is not using fully specified path and so webpack is not able to find the file?

>What I haven't been able to understand yet is why webpack is using .mjs file by default instead of .js...

I'll be honest, not totally sure! It works well with all the other bundlers 🤷🏼‍♀️

**Comment by LoicHuart** [comment] 2023-02-24 10:25
Indeed my problem came from there, here is my solution
Thanks for your help

```
const path = require('path');

module.exports = {
    webpack: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
        configure: {
            module: {
                rules: [
                    {
                        test: /\.m?js/,
                        resolve: {
                            fullySpecified: false
                        }
                    },
                ],
            },
        }
    },
};
```

**Comment by joshuaellis** [comment] 2023-02-24 10:34
Seems like there's a solution – i'm gonna close this issue but also pin it so others will see it if they have the problem.

Thanks for all the responsiveness, sorry there's nothing I can do this side.

**Comment by chenxsan** [comment] 2023-02-24 12:15
Just ran into this problem in an ESM project. The problem here is webpack requires `import/exports` in esm files to specify the extension due to the enabled [resolve.fullySpecified](https://webpack.js.org/configuration/module/#resolvefullyspecified), though some other bundlers might permit it without the extension.

In my case, here's the code causing the problem https://github.com/pmndrs/react-spring/blob/master/packages/core/src/index.ts#L25-L26

```ts
export * from '@react-spring/types/animated'
export * from '@react-spring/types/interpolation'
```
Which can be fixed by appending the `.js` extension:

```ts
export * from '@react-spring/types/animated.js'
export * from '@react-spring/types/interpolation.js'
```

@joshuaellis Would u accept a pull request to fix it?

**Comment by joshuaellis** [comment] 2023-02-24 17:40
Sure we can take a look at an experimental release for this! I'm wondering if we do something more similar to this – https://github.com/adobe/react-spectrum/pull/4038 as this just fixes the issue at hand instead of tackling the root of the issue...

**Comment by joepuzzo** [comment] 2023-02-24 19:14
@bpinto Can you post your final solve ? Im also having this issue and cant get my webpack configured correctly.

**Comment by joepuzzo** [comment] 2023-02-24 20:30
Update this does in fact work. Another package also happened to have a minor version release today that caused issues. Love when that happens :)
```js
 {
        test: /react-spring/i,
        resolve: {
          fullySpecified: false,
        },
      },
```

**Comment by joshuaellis** [comment] 2023-02-24 20:45
> Update this does in fact work. Another package also happened to have a minor version release today that caused issues. Love when that happens :)
> 
> ```js
> 
>  {
> 
>         test: /react-spring/i,
> 
>         resolve: {
> 
>           fullySpecified: false,
> 
>         },
> 
>       },
> 
> ```
> 
> 
> 
> 

You do appreciate this is due to the changes in ESM specs & webpack 4 being used? 😅

**Comment by chenxsan** [comment] 2023-02-25 01:58
`resolve.fullySpecified` was introduced in [webpack 5](https://github.com/webpack/webpack.js.org/issues/3975), so I don't think it's a webpack 4 problem.

**Comment by joshuaellis** [comment] 2023-02-25 15:09
Hey everyone (cc @chenxsan) – i've got an experimental release that _should_ work across on bundlers. The version number is `0.0.0-1f54fd5554e133fd353fcf3bd85edeac3562a1a0-20230225150642`

```shell
yarn add @react-spring/web@0.0.0-1f54fd5554e133fd353fcf3bd85edeac3562a1a0-20230225150642`
```

If people could confirm that'd be great, i've tested it in the following environments:

* next
* vite
* webpack4
* CRA

**Comment by CodyJasonBennett** [comment] 2023-02-25 16:27
This is not a bug in Webpack or similar. ESM requires usage of explicit file extensions in import specifiers (see [mandatory file extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions)). This can be fixed with the use of [`package#exports`](https://nodejs.org/api/packages.html#conditional-exports) if you permit multiple entrypoints.

**Comment by joshuaellis** [comment] 2023-02-25 17:32
I don't think anyone has said it was a bug with webpack @CodyJasonBennett :) I actually think from more research and discussion with a few devs on twitter a combination of `exports` and `main/module` are required to deliver the best package experience 💪🏼

**Comment by jamesguan** [comment] 2023-02-25 17:39
I am experiencing this exact same issue. ```
ERROR in ../../node_modules/@react-spring/core/dist/index.mjs 2082:0-45

Module not found: Error: Can't resolve '@react-spring/types/animated' in '/Users/razgriz/projects/peachai/OnePeach/node_modules/@react-spring/core/dist'
Did you mean 'animated.js'?
BREAKING CHANGE: The request '@react-spring/types/animated' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by chenxsan** [comment] 2023-02-26 13:04
> I don't think anyone has said it was a bug with webpack @CodyJasonBennett :) I actually think from more research and discussion with a few devs on twitter a combination of `exports` and `main/module` are required to deliver the best package experience 💪🏼

I've tested it against the webpack.js.org repository, works fine with webpack 5.

**Comment by bpinto** [comment] 2023-02-26 15:58
That didn't work on my testing, when I look at what files the package has locally, it is missing the `dist` folder:

```
docker@542d49841994:/src/app$ ls -lah node_modules/@react-spring/web/
total 20K
drwxr-xr-x 2 docker docker 4.0K Feb 26 15:47 .
drwxr-xr-x 8 docker docker 4.0K Feb 26 15:47 ..
-rw-r--r-- 1 docker docker 1.1K Feb 26 15:47 LICENSE
-rw-r--r-- 1 docker docker   41 Feb 26 15:47 README.md
-rw-r--r-- 1 docker docker 1.4K Feb 26 15:47 package.json
```

As you can see the package is using the correct version:

```
docker@a2a59dbbe706:/src/app$ cat node_modules/@react-spring/web/package.json
{
  "name": "@react-spring/web",
  "version": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./package.json": "./package.json"
  },
  "files": [
    "dist/*",
    "README.md",
    "LICENSE"
  ],
  "repository": "pmndrs/react-spring",
  "homepage": "https://github.com/pmndrs/react-spring#readme",
  "keywords": [
    "animated",
    "animation",
    "hooks",
    "motion",
    "react",
    "react-native",
    "spring",
    "typescript",
    "velocity"
  ],
  "license": "MIT",
  "author": "Paul Henschel",
  "maintainers": [
    "Josh Ellis (https://github.com/joshuaellis)"
  ],
  "dependencies": {
    "@react-spring/animated": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
    "@react-spring/core": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
    "@react-spring/shared": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
    "@react-spring/types": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818"
  },
  "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
  },
  "scripts": {
    "build": "tsup",
    "dev": "tsup"
  }
}
```

You can also confirm this via [npmjs](https://www.npmjs.com/package/@react-spring/web/v/0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818?activeTab=explore) Code tab.

**Comment by petatemarvin26** [comment] 2023-02-27 02:10
I install `^9.5.5` but npm gives me `9.7.0` 🤔

**Comment by abdoKa** [comment] 2023-02-27 08:14
@LoicHuart's solution is works for me. 
The config of the `cargo.config.ts`
1. remove `node_modules` and `yarn.lock`
2. add this config to the `cargo.config.ts`
```
 configure: {
      module: {
        rules: [
          {
            test: /\.m?js/,
            resolve: {
              fullySpecified: false
            }
          },
        ],
      },
    }
```
3. run `yarn `

**Comment by joshuaellis** [comment] 2023-02-27 08:16
> That didn't work on my testing, when I look at what files the package has locally, it is missing the `dist` folder:
> 
> ```
> docker@542d49841994:/src/app$ ls -lah node_modules/@react-spring/web/
> total 20K
> drwxr-xr-x 2 docker docker 4.0K Feb 26 15:47 .
> drwxr-xr-x 8 docker docker 4.0K Feb 26 15:47 ..
> -rw-r--r-- 1 docker docker 1.1K Feb 26 15:47 LICENSE
> -rw-r--r-- 1 docker docker   41 Feb 26 15:47 README.md
> -rw-r--r-- 1 docker docker 1.4K Feb 26 15:47 package.json
> ```
> 
> As you can see the package is using the correct version:
> 
> ```
> docker@a2a59dbbe706:/src/app$ cat node_modules/@react-spring/web/package.json
> {
>   "name": "@react-spring/web",
>   "version": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
>   "main": "dist/index.js",
>   "module": "dist/index.mjs",
>   "types": "dist/index.d.ts",
>   "exports": {
>     ".": {
>       "types": "./dist/index.d.ts",
>       "import": "./dist/index.mjs",
>       "require": "./dist/index.js"
>     },
>     "./package.json": "./package.json"
>   },
>   "files": [
>     "dist/*",
>     "README.md",
>     "LICENSE"
>   ],
>   "repository": "pmndrs/react-spring",
>   "homepage": "https://github.com/pmndrs/react-spring#readme",
>   "keywords": [
>     "animated",
>     "animation",
>     "hooks",
>     "motion",
>     "react",
>     "react-native",
>     "spring",
>     "typescript",
>     "velocity"
>   ],
>   "license": "MIT",
>   "author": "Paul Henschel",
>   "maintainers": [
>     "Josh Ellis (https://github.com/joshuaellis)"
>   ],
>   "dependencies": {
>     "@react-spring/animated": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
>     "@react-spring/core": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
>     "@react-spring/shared": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818",
>     "@react-spring/types": "0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818"
>   },
>   "peerDependencies": {
>     "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
>     "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
>   },
>   "scripts": {
>     "build": "tsup",
>     "dev": "tsup"
>   }
> }
> ```
> 
> You can also confirm this via [npmjs](https://www.npmjs.com/package/@react-spring/web/v/0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818?activeTab=explore) Code tab.

Thanks for that catch. Looks like the experimental release workflow wasn't building 🤦🏼‍♀️ back on this issue this AM :)

**Comment by joshuaellis** [comment] 2023-02-27 08:22
New experimental release that I believe should work – `0.0.0-40ac9039be0c657954e31ea7588bee4abbf1df1f-20230227081728` if people are interested in trying it out need more verification it works in the wild! 🤞🏼

**Comment by evamalininaa** [comment] 2023-02-27 09:05
With 0.0.0-40ac9039be0c657954e31ea7588bee4abbf1df1f-20230227081728 local build was fixed 🕺

**Comment by bpinto** [comment] 2023-02-27 11:26
Working for me as well 👍 Thank you! 🙇

**Closed** 2023-02-27 12:52 UTC
Labels: kind: bug
