### ISSUE TITLE
springs doesn't work if Canvas doesn't persist and three animated(...) was invoked somewhere in the project [bug]: 

### ISSUE THREAD

**Issue by mordv** [pmndrs/react-spring#2001] opened 2022-10-22 07:52 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [X] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.5.5

### What's Wrong?

If somewhere in the project HOC for fiber was created:
`const AnimatedBox = animatedThree(Box)`

The animation is dead for all web pages without the fiber's `Canvas`

### To Reproduce

Reproduced in codesanbox.
Try to comment out 9 line of codesandbox example - the thing will work as expected.

### Expected Behaviour

I expect that custom animated components wouldn't have any effect on pages without theejs.

### Link to repo

https://codesandbox.io/s/optimistic-clarke-urfiic?file=/src/App.tsx:344-382

**Comment by joshuaellis** [comment] 2022-10-22 13:42
Thanks for the report @mordv, this is a duplicate of #1586, here's a workaround whilst I work on a fix – https://github.com/pmndrs/react-spring/issues/1586#issuecomment-870778191

**Closed** 2022-10-22 13:42 UTC
Labels: template: bug
