### ISSUE TITLE
useTransition (version 9) opacity issue 

### ISSUE THREAD

**Issue by RexToCode** [pmndrs/react-spring#1207] opened 2020-11-25 17:31 UTC
I just upgraded to version 9, and trying to use the useTransition with opacity changes.  I tested the code by using some other css properties (other than opacity), and it worked fine.  I put "opacity: number", then the "style" immediately went red.  There was one case earlier having the same issue but claimed that it requires to use "%" for the unit instead of "number", and i tried putting % too....it doesn't work.  Can i please know if there's any changes on the unit requirement for opacity?  I didn't have this issue in version 8...

*** by the way, wondering if "animated" tag is replaced with "a" for useTransition V9.

**Comment by aleclarson** [comment] 2020-11-25 17:41
Probably a duplicate of #1102

**Comment by RexToCode** [comment] 2020-11-25 19:05
thanks for your quick response~~~
is there any possible chance the same code works in sandbox but not in VScode?  I just tried to copy and paste the same codes to my VScode....the "style" is in red again...

```
Type '{ opacity: SpringValue<number>; }' is not assignable to type '{ alignContent?: "initial" | "-moz-initial" | "inherit" | "revert" | "unset" | "end" | "baseline" | "start" | "center" | "normal" | "space-around" | "space-between" | "space-evenly" | ... 4 more ... | undefined; ... 794 more ...; matrix3d?: readonly [...] | ... 1 more ... | undefined; }'.
  Types of property 'opacity' are incompatible.
    Type 'SpringValue<number>' is not assignable to type '"initial" | "-moz-initial" | "inherit" | "revert" | "unset" | FluidValue<Globals, any> | undefined'.
      Type 'SpringValue<number>' is not assignable to type 'FluidValue<Globals, any>'.
        The types returned by 'get()' are incompatible between these types.
          Type 'number' is not assignable to type 'Globals'.  TS2322

    114 |       <div>
    115 |       {transitions((style, item, state) => {
  > 116 |         return <animated.div style={style}>Test</animated.div>;
        |                              ^
    117 |       })}
    118 |       </div>
    119 |       <div>
```

**Comment by aleclarson** [comment] 2020-11-25 21:00
You'll need to downgrade your `@types/react` or use `style={style as any}` until the next react-spring version is released.

**Closed** 2020-11-25 21:00 UTC
Labels: duplicate

**Comment by RexToCode** [comment] 2020-11-25 21:25
thanks Alec~
