### ISSUE TITLE
useTrail Animation has no transition effect ?

### ISSUE THREAD

**Issue by zejunking** [pmndrs/react-spring#1140] opened 2020-09-07 13:01 UTC
## 🐛 Bug Repor
Width from 1 to 100 has no transition effect and is instantly reached.
The code can run on V8. Is it caused by the new change of V9?
 Please forgive me for not finding the method in the document.

![image](https://user-images.githubusercontent.com/21262401/92390100-d74a4a00-f14c-11ea-8318-63c3a072faf5.png)

- `react-spring` v9.0.0-rc.3
- `react` v16.13.1

**Comment by aleclarson** [comment] 2020-09-07 14:58
Please provide a minimal sandbox (fork [this one](https://codesandbox.io/s/winter-wood-w37vz)) or `.git` url that shows the issue. 👍

**Comment by zejunking** [comment] 2020-09-08 03:22
> Please provide a minimal sandbox (fork [this one](https://codesandbox.io/s/winter-wood-w37vz)) or `.git` url that shows the issue. 👍

https://codesandbox.io/s/inspiring-faraday-tjsf6

**Comment by tomdohnal** [comment] 2020-09-23 08:09
I believe it's the same(-ish) issue I'm having here https://github.com/pmndrs/react-spring/issues/1118

**Comment by CodyJasonBennett** [comment] 2021-03-21 15:56
This is a duplicate of #1118, with multiple animations not being smoothly animated.

However, this looks to be working with what we're cooking up for v9.1.0.

![v9](https://user-images.githubusercontent.com/23324155/111911431-a029ef00-8a33-11eb-8043-05c6e92bf3db.gif)

**Closed by CodyJasonBennett** 2021-03-21 15:56 UTC
Labels: bug, v9
