### ISSUE TITLE
When using @react-spring/three v9  "apply" return errors

### ISSUE THREAD

**Issue by carllx** [pmndrs/react-spring#1272] opened 2021-02-02 21:54 UTC
## 🐛 Bug Report
When update to @react-spring/three v9 "apply" return errors

```javascript
import React, { useRef, useEffect } from 'react'
import { extend, useThree, useFrame } from 'react-three-fiber'
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer'
import { ShaderPass } from 'three/examples/jsm/postprocessing/ShaderPass'
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass'
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
....
import {useSpring} from "@react-spring/core"
import {a ,apply as applySpring} from "@react-spring/three"
applySpring(  {UnrealBloomPass } )
```
errors:
```
Object(...) is not a function
TypeError: Object(...) is not a function
 at Module.eval (webpack-internal:///./src/nd/components/Effects.js:31:67)
 at eval (webpack-internal:///./src/nd/components/Effects.js:175:30)
 at Module../src/nd/components/Effects.js (http://localhost:3000/_next/static/chunks/1.js:3095:1)
 at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1612301483115:873:31)
 at fn (http://localhost:3000/_next/static/chunks/webpack.js?ts=1612301483115:151:20)
 at Module.eval (webpack-internal:///./src/nd/components/app.js:13:66)
 at eval (webpack-internal:///./src/nd/components/app.js:253:30)
 at Module../src/nd/components/app.js (http://localhost:3000/_next/static/chunks/1.js:3119:1)
 at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1612301483115:873:31)
 at fn (http://localhost:3000/_next/static/chunks/webpack.js?ts=1612301483115:151:20)
```

and return Error in codesandbox example below
```
(0 , _three.apply) is not a function
```
## Expected behavior

(A clear and concise description of what you expected to happen.)

## Link to repro (highly encouraged)

https://codesandbox.io/s/glitch-react-three-fiber-react-spring-forked-mevhu?file=/src/index.js

## Environment
- "@react-spring/core": "^9.0.0-rc.3"
- "@react-spring/three": "^9.0.0-rc.3"
- "react": "^17.0.1"
- "react-spring": "^9.0.0-rc.3"
- "react-three-fiber": "5.3.18"
- "three": "^0.125.2"

**Comment by Yzrsah** [comment] 2021-03-23 22:16
@joshuaellis `apply` isn't existing in @react-spring/three V9
Is `apply` deprecated? What is the intended way to extend the catalog in V9?
Also it would be good to export the new name `extend` to match r3f naming convention for extending the catalog.

**Comment by joshuaellis** [comment] 2021-03-24 15:49
@carllx, @Yzrsah  I don't have a repo to look into this as the above link does not work, please supply one and we can look into it. Also, a repo of the expected behaviour would be helpful too.

**Comment by Yzrsah** [comment] 2021-04-05 19:13
@joshuaellis `apply` isn't existing cause it was removed, first with a deprecated message at around 9.0.0-beta8:
https://github.com/pmndrs/react-spring/blob/v9.0.0-beta.8/src/targets/three/index.ts
It was renamed to `animated.extend`: https://github.com/pmndrs/react-spring/blob/1e1c19d391dea7fce68d59d4ba6aace1adb50694/src/animated/createAnimatedComponent.tsx#L104
But `extend` was removed and moved over to some new code. And the `apply` deprecation was removed.
And then that new code was also removed (by Alec)

@aleclarson What did you have in mind for this?

**Comment by Yzrsah** [comment] 2021-04-05 19:18
@joshuaellis `apply` isn't existing cause it was removed, first with a deprecated message at around 9.0.0-beta8:
https://github.com/pmndrs/react-spring/blob/v9.0.0-beta.8/src/targets/three/index.ts

The replacement was `animated.extend`: https://github.com/pmndrs/react-spring/blob/1e1c19d391dea7fce68d59d4ba6aace1adb50694/src/animated/createAnimatedComponent.tsx#L104
But `extend` was removed and moved over to some new code. And the `apply` deprecation was removed.
And then that new code was also removed (by Alec)

@aleclarson What did you have in mind for this?

**Comment by mysterybear** [comment] 2021-04-19 17:35
https://github.com/pmndrs/react-three-fiber/issues/23#issuecomment-822450360 may be related

**Comment by joshuaellis** [comment] 2021-04-19 21:52
Closing because no one is providing a repo to debug this issue.

**Closed by joshuaellis** 2021-04-19 21:52 UTC
Labels: needs repro, potential bug, v9
