### ISSUE TITLE
yarn command fails with an error

### ISSUE THREAD

**Issue by nisarhassan12** [pmndrs/react-spring#1198] opened 2020-11-17 11:48 UTC
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

I was trying to set the repo up for contributing but the `yarn` command is failing with the below error:

![image](https://user-images.githubusercontent.com/46004116/99386737-bfcdd100-28f4-11eb-9690-ba889221a9b7.png)

## Expected behavior

(A clear and concise description of what you expected to happen.)

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment] 2020-11-17 18:16
Duplicate of #1182

See here: https://github.com/pmndrs/react-spring/issues/1182#issuecomment-715414997

**Closed by aleclarson** 2020-11-17 18:16 UTC
