### ISSUE TITLE
Weird behaviour with fast refresh in v9

### ISSUE THREAD

**Issue by callumbooth** [pmndrs/react-spring#1268] opened 2021-01-29 16:15 UTC
## 🐛 Bug Report

When initialising a spring with a function, when the code is rebuilT with fast refresh the initialised value is lost as soon as the component is re rendered

## To Reproduce

1. Go to https://codesandbox.io/s/happy-wright-0tlnq?file=/pages/index.js
2. Open the console and see than there is an object with an "xy" value.
3. Edit the "editMe" const and wait for fast refresh to update.
4. See that the console log with fire again with the "xy" value
5. Scroll down on the browsers and see that the object no longer contains the value "xy"

## Expected behavior

The initial value shouldn't be lost after a fast refresh.

## Link to repro (highly encouraged)

https://codesandbox.io/s/happy-wright-0tlnq?file=/pages/index.js

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v17.0.1

**Comment by lourd** [comment] 2021-01-30 18:23
Here's another, slightly simpler reproduction - https://codesandbox.io/s/stupefied-williams-vs3rg?file=/src/App.tsx. It looks like the `_phase` property of the `SpringValue` is going from `ACTIVE` to `DISPOSED`.

I'd go as far to say Fast Refresh is broken with regard to `useSpring` in v9.

**Comment by aleclarson** [comment] 2021-01-30 19:18
This will be fixed in `9.0.0-rc.4` (see 4b8cd966d593c20f9e4dff2bac5d24d7a8c92413). You can clone the `v9` branch in the meantime.

**Comment by callumbooth** [comment] 2021-02-01 14:46
> This will be fixed in `9.0.0-rc.4` (see [4b8cd96](https://github.com/pmndrs/react-spring/commit/4b8cd966d593c20f9e4dff2bac5d24d7a8c92413)). You can clone the `v9` branch in the meantime.

Great to hear. Any idea when rc4 might be released?

**Comment by joshuaellis** [comment] 2021-03-18 17:39
#1330

**Closed by joshuaellis** 2021-03-18 17:39 UTC
Labels: fix ready
