### ISSUE TITLE
[bug]:  conflict between the trail prop and the exitBeforeEnter prop.

### ISSUE THREAD

**Issue by bessim-dev** [pmndrs/react-spring#1942] opened 2022-07-19 08:33 UTC
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.5.0

### What's Wrong?

i'm trying to build a staggering effect with the useTransition, I have an object containing 2 arrays and I change the index each time to select one array and animate that enter/leave of data but it breaks whenever I change the array. 

### To Reproduce

switch between 2 arrays, animate that with useTransition and make sure to have `trail` and `exitBeforeEnter` prop

### Expected Behaviour

1- on enter, the items in the array will animate in (in stagger effect)
2- when I change the index the old items animate out and the new ones animate in

### Link to repo

https://codesandbox.io/s/stagger-qmtc9t?file=/src/App.js

**Comment by joshuaellis** [comment] 2022-07-21 15:30
this is a duplicate of #1868 so closing it in favour of that issue.

**Closed by joshuaellis** 2022-07-21 15:30 UTC
Labels: kind: bug, area: core
